spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    baseline-description: "baseline esquema inicial"
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/finanzas_uat}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:finanzas}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}
